(()=>{"use strict";
const KEY="wonder-verse-becoming-atlas-v1";
const chapters=[
{n:"01",title:"Notice",kicker:"The moment the story changed",intro:"Before you fix anything, tell the truth about what happened. Not the polished truth. The useful one.",prompts:[["notice_moment","When did you first know something was wrong—even before you could explain it?"],["notice_signal","What did your body, behaviour or intuition notice before your mind admitted it?"],["notice_story","What story did you tell yourself so you could avoid facing it?"]] },
{n:"02",title:"Own",kicker:"Responsibility without self-punishment",intro:"Owning your part is not the same as carrying all the blame. Take what is yours. Leave what is not.",prompts:[["own_part","What was your part in the mistake—specifically, without excuses or exaggeration?"],["own_impact","Who was affected, and what may the situation have felt like from their side?"],["own_pattern","Was this a one-time error, or a pattern you have been reluctant to name?"]] },
{n:"03",title:"Repair",kicker:"Make the learning visible",intro:"An apology is a beginning. Repair is the evidence that you understood.",prompts:[["repair_action","What did you change in the relationship, workplace or routine after the mistake?"],["repair_conversation","What conversation still needs to happen—and what truth are you avoiding in it?"],["repair_proof","What would consistent changed behaviour look like for the next 30 days?"]] },
{n:"04",title:"Trust",kicker:"When intuition asks for courage",intro:"Intuition is not always a command. Sometimes it is a question that deserves a proper hearing.",prompts:[["trust_time","When did you let your intuition win? What did it know that the evidence had not caught up with yet?"],["trust_cost","What hard thing do you know you are meant to do—and what is the honest cost of not doing it?"],["trust_test","What small, reversible action could test your instinct without gambling your stability?"]] },
{n:"05",title:"Begin",kicker:"Start at your actual starting line",intro:"Someone else being further ahead is not evidence that you are late. It is evidence that the road exists.",prompts:[["begin_compare","Whose middle are you comparing with your beginning? What does that comparison make you forget?"],["begin_level","If you accepted that you are a beginner, what would you practise instead of pretending to know?"],["begin_next","What is the next action small enough to complete, but real enough to count?"]] }
];
const fields=[["north","North star","What matters enough to organise your life around?"],["long","Long horizon","What would you be proud to have built in five years?"],["season","This season","What deserves your focus for the next 90 days?"],["insecurity","The voice that shrinks you","What insecurity appears when you move towards the work?"],["reply","Your grounded reply","What will you say back when that insecurity arrives?"]];
let state={answers:{},milestones:[]};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||"{}")} }catch{}
const $=s=>document.querySelector(s);let saveTimer;
const escape=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function persist(message="Saved privately on this device."){clearTimeout(saveTimer);$("#saveStatus").textContent="Saving…";saveTimer=setTimeout(()=>{localStorage.setItem(KEY,JSON.stringify(state));$("#saveStatus").textContent=message},300)}
function progress(){$("#progress").textContent=Object.values(state.answers).filter(v=>String(v).trim()).length}
function answerInput(e){state.answers[e.target.dataset.key]=e.target.value;progress();persist()}
function renderQuestions(){const symbols=["○","◇","↗","△","✦"];
  $("#chapters").innerHTML=chapters.map((c,i)=>`<article class="chapter"><div class="chapter-side"><span class="chapter-number">${c.n}</span><span class="chapter-symbol" aria-hidden="true">${symbols[i]}</span></div><div class="chapter-body"><p class="kicker">${c.kicker}</p><h3>${c.title}</h3><p class="chapter-intro">${c.intro}</p><div class="prompts">${c.prompts.map(([k,q])=>`<label class="prompt"><span>${q}</span><textarea data-key="${k}" placeholder="Write the answer you would not say automatically…" rows="3">${escape(state.answers[k]||"")}</textarea></label>`).join("")}</div></div></article>`).join("");
  $("#coordinates").innerHTML=fields.map(([k,l,h])=>`<label class="coordinate"><span>${l}</span><small>${h}</small><textarea data-key="${k}" rows="3" placeholder="Write here…">${escape(state.answers[k]||"")}</textarea></label>`).join("");
  document.querySelectorAll("textarea[data-key]").forEach(el=>el.addEventListener("input",answerInput));progress();
}
function renderMilestones(){const root=$("#milestones");if(!state.milestones.length){root.innerHTML='<div class="empty"><span>＋</span><p>Your first marker can be small.<br>Small and real beats impressive and imaginary.</p></div>';return}
 root.innerHTML=state.milestones.map((m,i)=>`<article class="milestone"><button type="button" data-remove="${m.id}" aria-label="Remove ${escape(m.title)}">×</button><span class="milestone-index">${String(i+1).padStart(2,"0")}</span><small>${escape(m.horizon)}</small><h4>${escape(m.title)}</h4>${m.truth?`<p><b>What may get in the way:</b> ${escape(m.truth)}</p>`:""}<p><b>Next:</b> ${escape(m.action)}</p></article>`).join("");
 root.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{state.milestones=state.milestones.filter(m=>m.id!==Number(b.dataset.remove));renderMilestones();persist()});
}
$("#addMilestone").onclick=()=>{const title=$("#milestoneTitle").value.trim(),action=$("#milestoneAction").value.trim();if(!title||!action){$("#saveStatus").textContent="Name the milestone and its next action first.";return}state.milestones.push({id:Date.now(),horizon:$("#horizon").value,title,truth:$("#milestoneTruth").value.trim(),action});["#milestoneTitle","#milestoneTruth","#milestoneAction"].forEach(s=>$(s).value="");renderMilestones();persist("A new point has been added to your map.")};
$("#downloadAtlas").onclick=()=>{const lines=["THE BECOMING ATLAS","A private map of what I noticed, owned, repaired, trusted and began",""];chapters.forEach(c=>{lines.push(`${c.n} — ${c.title.toUpperCase()}`);c.prompts.forEach(([k,q])=>lines.push(`\n${q}\n${state.answers[k]||"—"}`));lines.push("")});lines.push("MY FORWARD MAP");fields.forEach(([k,l])=>lines.push(`\n${l}:\n${state.answers[k]||"—"}`));lines.push("\nMILESTONES");state.milestones.forEach(m=>lines.push(`\n[${m.horizon}] ${m.title}\nTruth: ${m.truth||"—"}\nNext action: ${m.action}`));const blob=new Blob([lines.join("\n")],{type:"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="my-becoming-atlas.txt";a.click();URL.revokeObjectURL(a.href)};
renderQuestions();renderMilestones();if(Object.keys(state.answers).length||state.milestones.length)$("#saveStatus").textContent="Saved privately on this device.";
})();
