(() => {
  "use strict";

  const years = {
    year1: { number:"01", title:"Build the map before memorising the streets.", text:"Foundational science arrives quickly. Your task is to connect structure, function and language without treating every lecture slide as equally important.", reality:"It is normal to feel as if everyone else already speaks medicine. Most people are translating in real time.", focus:[["Anatomy & histology","Structure, spatial relationships and normal tissue"],["Physiology","Mechanisms, regulation and homeostasis"],["Biochemistry & genetics","Molecules connected to living systems"],["Professional identity","Communication, ethics and reflective practice"]] },
    year2: { number:"02", title:"Connect mechanisms to what goes wrong.", text:"Move from normal function into pathology, microbiology, immunology and pharmacology. Mechanisms matter more than disconnected lists.", reality:"Forgetting is not evidence that you cannot do medicine. Retrieval and revisiting are part of the curriculum your brain actually follows.", focus:[["Pathology","Injury, adaptation and disease mechanisms"],["Pharmacology","Targets, effects, harms and safe prescribing"],["Microbiology & immunity","Host, pathogen and clinical context"],["Systems integration","Symptoms connected back to mechanism"]] },
    year3: { number:"03", title:"The patient changes the shape of the knowledge.", text:"Early clinical placements turn neat textbook patterns into real people with incomplete histories, uncertainty and competing needs.", reality:"You do not need to perform confidence. Ask clearly, examine respectfully and tell your supervisor what you do not know.", focus:[["History taking","Open questions, structure and listening"],["Physical examination","Purposeful sequence and patient comfort"],["Clinical reasoning","Problem representation and differentials"],["Team practice","Handover, feedback and escalation"]] },
    year4: { number:"04", title:"Think across specialties without losing the whole person.", text:"Clinical rotations deepen. Build reusable reasoning patterns while noticing how context changes risk, presentation and care.", reality:"A difficult rotation is not a verdict on your future specialty—or your worth.", focus:[["Medicine & surgery","Priorities, investigations and management"],["Paediatrics & obstetrics","Development, physiology and family-centred care"],["Mental health","Safety, formulation and humane language"],["Evidence use","Guidelines, uncertainty and shared decisions"]] },
    year5: { number:"05", title:"Move from explaining to safely contributing.", text:"Senior clinical learning is about synthesis, prioritisation and recognising the edge of your competence.", reality:"Being useful includes noticing deterioration, communicating early and asking for help. Independence is not isolation.", focus:[["Acute care","ABCDE, urgency and escalation"],["Prescribing safety","Indications, interactions and monitoring"],["OSCE integration","Communication joined to clinical action"],["Career exploration","Values, environments and honest fit"]] },
    final: { number:"F", title:"Prepare for responsibility, not a performance of perfection.", text:"Consolidate common presentations, safe first actions, handover and the practical realities of entering supervised practice.", reality:"Final year can contain pride and grief at the same time. You are finishing one identity before you feel ready for the next.", focus:[["Readiness for practice","Common problems and safe initial management"],["Entrustable work","Documentation, handover and follow-through"],["Licensing milestones","Confirm your jurisdiction’s requirements"],["Transition planning","Support, rest and realistic systems"]] },
    early: { number:"→", title:"The first year with a name badge and real responsibility.", text:"Early practice asks for organisation, humility, communication and recovery—not instant mastery of every clinical situation.", reality:"If you are persistently distressed, unsafe or unable to function, a motivational quote is not enough. Contact local professional, workplace or emergency support.", focus:[["Task management","Priorities, jobs lists and closing loops"],["Escalation","Recognising concern and calling early"],["Patient communication","Clarity, consent and uncertainty"],["Sustainable practice","Debriefing, boundaries and help-seeking"]] }
  };

  const exams = [
    {name:"GAMSAT",country:"Australia",phase:"admission",label:"Admission",description:"Graduate-entry admissions test used by participating programs. Eligibility and use depend on the university.",url:"https://gamsat.acer.org/"},
    {name:"UCAT ANZ",country:"Australia",phase:"admission",label:"Admission",description:"Admissions test used by participating Australian and New Zealand medicine, dentistry and clinical-science programs.",url:"https://www.ucat.edu.au/"},
    {name:"AMC standard pathway",country:"Australia",phase:"licensing",label:"IMG registration",description:"For eligible international medical graduates: AMC CAT MCQ plus the Clinical Examination or accredited workplace-based assessment.",url:"https://www.amc.org.au/pathways/standard-pathway/"},
    {name:"MCAT",country:"United States",phase:"admission",label:"Admission",description:"Medical-school admissions examination covering scientific foundations, reasoning and behavioural and social science concepts.",url:"https://students-residents.aamc.org/about-mcat-exam/about-mcat-exam"},
    {name:"USMLE Step 1",country:"United States",phase:"licensing",label:"Licensing sequence",description:"Tests understanding and application of foundational science relevant to medical practice. Check current eligibility and reporting rules.",url:"https://www.usmle.org/step-exams/step-1"},
    {name:"USMLE Step 2 CK",country:"United States",phase:"licensing",label:"Licensing sequence",description:"Assesses application of clinical knowledge for supervised patient care, including health promotion and disease prevention.",url:"https://www.usmle.org/step-exams/step-2-ck"},
    {name:"USMLE Step 3",country:"United States",phase:"licensing",label:"Licensing sequence",description:"A later component of the US medical licensing sequence. Eligibility differs from earlier Steps.",url:"https://www.usmle.org/step-exams/step-3"},
    {name:"UCAT",country:"United Kingdom",phase:"admission",label:"Admission",description:"Computer-based admissions test used by participating UK and partner universities for medicine and dentistry selection.",url:"https://www.ucat.ac.uk/"},
    {name:"GAMSAT (selected programs)",country:"United Kingdom",phase:"admission",label:"Graduate admission",description:"Used by some graduate-entry programs. Applicants must check each university’s current requirements.",url:"https://gamsat.acer.org/university-admission-uk"},
    {name:"Medical Licensing Assessment",country:"United Kingdom",phase:"degree",label:"During UK degree",description:"UK students take the MLA within their degree through an applied knowledge test and clinical and professional skills assessment.",url:"https://www.gmc-uk.org/education/medical-licensing-assessment"},
    {name:"PLAB",country:"United Kingdom",phase:"licensing",label:"IMG registration",description:"International graduate pathway aligned with MLA requirements; it continues to be called PLAB for practical candidate information.",url:"https://www.gmc-uk.org/education/medical-licensing-assessment/plab-and-the-mla"},
    {name:"MCAT (school-dependent)",country:"Canada",phase:"admission",label:"Admission",description:"Used by some Canadian medical schools. Each institution determines whether and how it uses the score.",url:"https://students-residents.aamc.org/about-mcat-exam/about-mcat-exam"},
    {name:"MCCQE",country:"Canada",phase:"licensing",label:"Licensing",description:"A one-day computer-based examination for eligible Canadian and international candidates; formerly called MCCQE Part I.",url:"https://mcc.ca/examinations-assessments/mccqe/"},
    {name:"NEET-UG",country:"India",phase:"admission",label:"Admission",description:"National entrance examination for admission to MBBS programs. Confirm current counselling and eligibility rules officially.",url:"https://www.nmc.org.in/neet/neet-ug/"},
    {name:"NEET-PG",country:"India",phase:"postgraduate",label:"Postgraduate admission",description:"Entrance examination for postgraduate medical courses. Rules and schedules should be checked with current authorities.",url:"https://www.nmc.org.in/neet/neet-pg/"},
    {name:"FMGE",country:"India",phase:"licensing",label:"Foreign graduate screening",description:"Screening examination for relevant foreign medical graduates. Check NBEMS and NMC for current applicability.",url:"https://natboard.edu.in/viewnbeexam?exam=fmge"},
    {name:"UCAT ANZ",country:"New Zealand",phase:"admission",label:"Admission",description:"Used by participating Australia and New Zealand programs alongside other selection requirements.",url:"https://www.ucat.edu.au/"},
    {name:"NZREX Clinical",country:"New Zealand",phase:"licensing",label:"IMG registration",description:"Clinical registration examination for eligible international medical graduates who are not eligible through another pathway.",url:"https://www.mcnz.org.nz/registration/getting-registered/registration-exam-nzrex/"},
    {name:"GAMSAT",country:"Ireland",phase:"admission",label:"Graduate admission",description:"Used for entry to participating graduate-entry programs. University eligibility and application processes still apply.",url:"https://gamsat.acer.org/university-admission-ireland"}
  ];

  const resources = [
    {id:1,title:"The Cardiac Cycle Without the Circle Diagram Panic",discipline:"Physiology",mode:"Concept guide",stage:"Years 1–2",color:"blue",description:"Pressure, volume, valves and heart sounds connected as one changing story.",objective:"Explain each phase using pressure gradients rather than memorised arrows.",sections:["Prerequisite check","Mechanism map","Clinical connection","Quick reflect"]},
    {id:2,title:"Brachial Plexus: Build It Before Naming It",discipline:"Anatomy",mode:"Active recall",stage:"Year 1",color:"yellow",description:"A reconstruction exercise that moves from roots to terminal branches.",objective:"Recreate the organisation and link lesions to functional findings.",sections:["Blank reconstruction","Motor and sensory clues","Lesion prompts","Teach-back"]},
    {id:3,title:"Inflammation: Helpful, Harmful, Contextual",discipline:"Pathology",mode:"Concept guide",stage:"Years 1–2",color:"coral",description:"Acute and chronic inflammation without reducing either to a list of cells.",objective:"Connect triggers, mediators, vascular change, cellular response and outcomes.",sections:["Core mechanism","Tissue story","Clinical pattern","Retrieval grid"]},
    {id:4,title:"Antibiotics and the Cost of Certainty",discipline:"Pharmacology",mode:"Clinical case",stage:"Years 2–4",color:"green",description:"A prescribing case about likely source, patient factors and antimicrobial stewardship.",objective:"Justify what information is needed before selecting, withholding or reviewing therapy.",sections:["Patient context","Mechanism comparison","Safety check","Review plan"]},
    {id:5,title:"Microbes Have Context Too",discipline:"Microbiology",mode:"Concept guide",stage:"Years 1–2",color:"green",description:"Colonisation, contamination and infection compared through clinical context.",objective:"Interpret a microbiology result without treating organism detection as automatic disease.",sections:["Definitions","Specimen quality","Host context","Clinical reasoning"]},
    {id:6,title:"The Breathless Patient",discipline:"Clinical reasoning",mode:"Clinical case",stage:"Years 3–Final",color:"blue",description:"Prioritise immediate safety while building a broad mechanism-based differential.",objective:"Organise causes of breathlessness and identify what must happen before diagnostic certainty.",sections:["Initial priorities","Focused history","Examination","Differential by mechanism"]},
    {id:7,title:"Explain Consent Without Sounding Scripted",discipline:"Communication",mode:"Skills station",stage:"Years 2–Final",color:"yellow",description:"Practise capacity, voluntariness, material risk and a genuine check of understanding.",objective:"Conduct a consent conversation that is legally aware and recognisably human.",sections:["Opening","Information","Uncertainty","Teach-back"]},
    {id:8,title:"ECG Orientation: What Am I Actually Looking At?",discipline:"Cardiology",mode:"Active recall",stage:"Years 2–Final",color:"coral",description:"Rate, rhythm, axis and intervals through repeatable observation before interpretation.",objective:"Use a consistent ECG sequence and separate description from conclusion.",sections:["Calibration","Sequence","Pattern prompts","Escalation clues"]},
    {id:9,title:"A Safe Handover Is a Clinical Skill",discipline:"Clinical skills",mode:"Skills station",stage:"Years 3–Early practice",color:"green",description:"Turn scattered patient information into a concise, actionable handover.",objective:"Communicate situation, background, assessment and recommendation with explicit uncertainty.",sections:["Prioritise","Structure","Closed-loop check","Reflection"]},
    {id:10,title:"When You Cannot Remember Why You Started",discipline:"Professional identity",mode:"Reflection",stage:"All stages",color:"blue",description:"A short, non-performative reflection for difficult placements and emotionally heavy weeks.",objective:"Notice what is happening, identify support and choose one proportionate next action.",sections:["Name it","Separate fact from story","Choose support","Close gently"]},
    {id:11,title:"Renal Compensation Without Magical Kidneys",discipline:"Physiology",mode:"Active recall",stage:"Years 1–3",color:"yellow",description:"Acid–base compensation connected to time, physiology and expected change.",objective:"Reason through primary disturbance and appropriate compensation step by step.",sections:["Pattern check","Compensation logic","Worked cases","Error traps"]},
    {id:12,title:"Fever in a Child: Speak to the Family Too",discipline:"Paediatrics",mode:"Clinical case",stage:"Years 3–Final",color:"coral",description:"Assessment priorities joined to age, red flags, hydration and family communication.",objective:"Structure a safe educational approach while keeping the child and carer within the conversation.",sections:["Immediate assessment","History","Communication","Safety-net reasoning"]}
  ];

  const yearPanel=document.querySelector("#yearPanel");
  function renderYear(key){const item=years[key];yearPanel.innerHTML=`<div class="year-summary"><span class="year-number">${item.number}</span><h3>${item.title}</h3><p>${item.text}</p><div class="reality-note"><strong>The part nobody puts on the timetable</strong><br>${item.reality}</div></div><div class="year-details"><h4>Useful focus for this stage</h4><div class="focus-grid">${item.focus.map(([title,text])=>`<div class="focus-item"><strong>${title}</strong><span>${text}</span></div>`).join("")}</div><a class="stage-action" href="#library">Open relevant learning resources →</a></div>`}
  document.querySelectorAll("[data-year]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-year]").forEach(item=>item.setAttribute("aria-selected","false"));button.setAttribute("aria-selected","true");renderYear(button.dataset.year)}));renderYear("year1");

  let phase="all";const examGrid=document.querySelector("#examGrid"),countryFilter=document.querySelector("#countryFilter");
  function renderExams(){const country=countryFilter.value;const visible=exams.filter(exam=>(country==="all"||exam.country===country)&&(phase==="all"||exam.phase===phase));examGrid.innerHTML=visible.length?visible.map(exam=>`<article class="exam-card" data-phase="${exam.phase}"><div class="exam-top"><span>${exam.country}</span><span class="phase-badge">${exam.label}</span></div><h3>${exam.name}</h3><p>${exam.description}</p><a href="${exam.url}" target="_blank" rel="noopener noreferrer">Open official authority ↗</a></article>`).join(""):`<div class="exam-empty">No pathway in this filter yet. Try “All stages” or another region.</div>`}
  countryFilter.addEventListener("change",renderExams);document.querySelectorAll("[data-phase]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-phase]").forEach(item=>item.classList.remove("active"));button.classList.add("active");phase=button.dataset.phase;renderExams()}));renderExams();

  const resourceGrid=document.querySelector("#resourceGrid"),resourceSearch=document.querySelector("#resourceSearch"),disciplineFilter=document.querySelector("#disciplineFilter"),modeFilter=document.querySelector("#modeFilter"),resourceCount=document.querySelector("#resourceCount"),resourceEmpty=document.querySelector("#resourceEmpty"),dialog=document.querySelector("#resourceDialog"),dialogContent=document.querySelector("#dialogContent");
  [...new Set(resources.map(item=>item.discipline))].sort().forEach(value=>{const option=document.createElement("option");option.value=value;option.textContent=value;disciplineFilter.append(option)});
  function renderResources(){const q=resourceSearch.value.trim().toLowerCase(),discipline=disciplineFilter.value,mode=modeFilter.value;const visible=resources.filter(item=>`${item.title} ${item.discipline} ${item.description}`.toLowerCase().includes(q)&&(discipline==="all"||item.discipline===discipline)&&(mode==="all"||item.mode===mode));resourceGrid.innerHTML=visible.map(item=>`<article class="resource-card ${item.color}"><div class="resource-top"><span>${item.discipline}</span><span>${item.mode}</span></div><h3>${item.title}</h3><p>${item.description}</p><div class="resource-meta"><span>${item.stage}</span><span>·</span><span>Guided learning</span></div><button type="button" data-resource="${item.id}">Preview resource <span>→</span></button></article>`).join("");resourceCount.textContent=`${visible.length} learning ${visible.length===1?"doorway":"doorways"} found`;resourceEmpty.hidden=visible.length>0}
  [resourceSearch,disciplineFilter,modeFilter].forEach(el=>el.addEventListener(el===resourceSearch?"input":"change",renderResources));document.querySelector("#clearResourceFilters").addEventListener("click",()=>{resourceSearch.value="";disciplineFilter.value="all";modeFilter.value="all";renderResources()});resourceGrid.addEventListener("click",event=>{const button=event.target.closest("[data-resource]");if(!button)return;const item=resources.find(resource=>resource.id===Number(button.dataset.resource));dialogContent.innerHTML=`<p class="eyebrow">${item.discipline} · ${item.mode} · ${item.stage}</p><h2 id="dialogTitle">${item.title}</h2><p>${item.description}</p><div class="dialog-objective"><strong>Learning intention</strong><br>${item.objective}</div><div class="dialog-grid"><div><h4>Inside this resource</h4><ul>${item.sections.map(section=>`<li>${section}</li>`).join("")}</ul></div><div><h4>How to use it</h4><p>Attempt the opening prompt before reading. Explain the mechanism aloud, then return to the clinical connection and identify what remains uncertain.</p></div></div><div class="dialog-prompt"><h4>Human checkpoint</h4><p>What would this knowledge change for a patient, colleague or decision?</p></div>`;dialog.showModal()});renderResources();

  document.querySelector("#dialogClose").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",event=>{const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()});
  document.querySelector("#checkCase").addEventListener("click",()=>{const selected=document.querySelector('input[name="caseStep"]:checked'),feedback=document.querySelector("#caseFeedback");feedback.className="case-feedback";if(!selected){feedback.textContent="Choose an option first. The pause before action is part of the reasoning.";return}if(selected.value==="history"){feedback.classList.add("correct");feedback.innerHTML="<strong>Good first move.</strong> A focused history helps clarify onset, bleeding or dietary history, pregnancy possibility, infection, cardiopulmonary red flags, medicines and functional impact. Examination and investigations would follow according to context and local practice."}else{feedback.classList.add("caution");feedback.innerHTML="<strong>Slow the jump.</strong> The presentation may suggest possibilities, but safe reasoning still needs red-flag assessment, a focused history, examination and appropriate investigation. A plausible diagnosis is not yet a complete clinical process."}});
  const resets={overwhelmed:["Reduce the field","Close every tab except the one task needed for the next 15 minutes. Write one question you are trying to answer—not an entire subject you are trying to conquer."],behind:["Replace comparison with coordinates","Name what you have actually completed, what is required next and who can clarify priorities. “Behind everyone” is a feeling; a list gives you a location."],mistake:["Move from shame to a safe response","If patient safety may be involved, follow local escalation and disclosure processes immediately. Then debrief with an appropriate supervisor and identify the system and knowledge factors—not only self-blame."],numb:["Treat numbness as information","Pause nonessential study. Eat, hydrate and contact someone safe. If this persists, affects functioning or worries you, seek confidential professional or university support rather than trying to out-study it."]};
  document.querySelectorAll("[data-reset]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-reset]").forEach(item=>item.classList.remove("active"));button.classList.add("active");const [title,text]=resets[button.dataset.reset];document.querySelector("#resetCard").innerHTML=`<strong>${title}</strong><p>${text}</p>`}));
  const mobileMenu=document.querySelector("#mobileMenu"),mainNav=document.querySelector("#mainNav");mobileMenu.addEventListener("click",()=>{const open=mainNav.classList.toggle("nav-open");mobileMenu.setAttribute("aria-expanded",String(open));mobileMenu.textContent=open?"×":"☰"});mainNav.addEventListener("click",event=>{if(event.target.closest("a")){mainNav.classList.remove("nav-open");mobileMenu.setAttribute("aria-expanded","false");mobileMenu.textContent="☰"}});
})();
